import './todoItem.css';
import {createButton} from './button';
const createTodoItem = (id, text, completed, onToggle, onDelete) => {
  const item = document.createElement('div');
  item.className = `todoItem${completed ? ' completed' : ''}`;
  const checkbox = document.createElement('input');
  checkbox.type = 'checkbox';
  checkbox.checked = completed;
  checkbox.id = `todo-${id}`;
  checkbox.addEventListener('change', onToggle);
  const label = document.createElement('label');
  label.textContent = text;
  label.htmlFor = `todo-${id}`;
  const deleteBtn = createButton('Delete', onDelete);
  item.appendChild(checkbox);
  item.appendChild(label);
  item.appendChild(deleteBtn);
  return item;
};
export {createTodoItem};
